version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 1972:1972
      - 52773:52773
      - 51773:51773
    volumes:
      - ./:/durable